-- MySQL Script generated by MySQL Workbench
-- 02/06/15 15:54:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema high-school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema high-school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `high-school` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `high-school` ;

-- -----------------------------------------------------
-- Table `high-school`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `high-school`.`Student` (
  `id_student` INT NOT NULL AUTO_INCREMENT,
  `registration_number` INT NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  PRIMARY KEY (`id_student`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `high-school`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `high-school`.`Teacher` (
  `id_teacher` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  PRIMARY KEY (`id_teacher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `high-school`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `high-school`.`Course` (
  `id_Course` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `total_hours` INT NOT NULL,
  `Teacher_id_teacher` INT NOT NULL,
  PRIMARY KEY (`id_Course`, `Teacher_id_teacher`),
  INDEX `fk_Course_Teacher1_idx` (`Teacher_id_teacher` ASC),
  CONSTRAINT `fk_Course_Teacher1`
    FOREIGN KEY (`Teacher_id_teacher`)
    REFERENCES `high-school`.`Teacher` (`id_teacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `high-school`.`Student_has_Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `high-school`.`Student_has_Course` (
  `Student_id_student` INT NOT NULL,
  `Course_id_Course` INT NOT NULL,
  `Note1` FLOAT NOT NULL,
  `Note2` FLOAT NOT NULL,
  `Note3` FLOAT NOT NULL,
  `Final` FLOAT NOT NULL,
  PRIMARY KEY (`Student_id_student`, `Course_id_Course`),
  INDEX `fk_Student_has_Course_Course1_idx` (`Course_id_Course` ASC),
  INDEX `fk_Student_has_Course_Student_idx` (`Student_id_student` ASC),
  CONSTRAINT `fk_Student_has_Course_Student`
    FOREIGN KEY (`Student_id_student`)
    REFERENCES `high-school`.`Student` (`id_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Course_Course1`
    FOREIGN KEY (`Course_id_Course`)
    REFERENCES `high-school`.`Course` (`id_Course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `high-school`.`Turn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `high-school`.`Turn` (
  `id_Turn` INT NOT NULL AUTO_INCREMENT,
  `begin` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `Course_id_Course` INT NOT NULL,
  `Course_Teacher_id_teacher` INT NOT NULL,
  PRIMARY KEY (`id_Turn`, `Course_id_Course`, `Course_Teacher_id_teacher`),
  INDEX `fk_Turn_Course1_idx` (`Course_id_Course` ASC, `Course_Teacher_id_teacher` ASC),
  CONSTRAINT `fk_Turn_Course1`
    FOREIGN KEY (`Course_id_Course` , `Course_Teacher_id_teacher`)
    REFERENCES `high-school`.`Course` (`id_Course` , `Teacher_id_teacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
